# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Samposium
tagline:          'The Exciting Adventures of Sam'
description:      'The Exciting Adventures of Sam'
url:              http://samstudio8.github.io

author:
  name:           'Sam Nicholls'
  url:            http://samnicholls.net

paginate:         5

