# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            samstudio8
tagline:          'Hoot hoot'
description:      'Hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot hoot'
url:              http://samstudio8.github.io

author:
  name:           'Sam Nicholls'
  url:            http://samnicholls.net

paginate:         5

