# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Samposium
tagline:          'The Exciting Adventures of Sam'
description:      'CompBio PhD at Aberystwyth University, currently visiting KU Leuven, Belgium. I tell computers to do things, then I write about how it all went wrong.'
url:              https://samstudio8.github.io

author:
  name:           'Sam Nicholls'
  url:            http://samnicholls.net

paginate:         3

